- name: iptables-services install
  package:
    name: iptables-services
    state: present

- name: firewalld install
  package:
    name: firewalld
    state: absent

- name: iptables is configured
  template:
    src: "iptables.j2"
    dest: "/etc/sysconfig/iptables"
    owner: root
    group: root
    mode: 0600

# ip6tables
- name: ip6tables is configured
  template:
    src: "ip6tables.j2"
    dest: "/etc/sysconfig/ip6tables"
    owner: root
    group: root
    mode: 0600
