- include: CentOS.yml
  when: "ansible_os_family == 'RedHat'"
  tags: secure

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: secure

- include: Debian.yml
  when: ansible_distribution == "Debian"
  tags: secure
